In [1]:
import pandas as pd

In [48]:
df_train = pd.read_pickle("../data/interim/Train_extern_git_feat_pid_-1.pickle")

In [63]:
df_test = pd.read_pickle("../data/interim/Test_extern_git_feat_pid_-1.pickle")

In [6]:
df_train.tail()

,o1,o2,d1,d2,mode_feas_0,mode_feas_1,mode_feas_2,mode_feas_3,mode_feas_4,mode_feas_5,...,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65
499995,116.32,39.62,116.45,39.91,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
499996,116.35,39.90,116.34,39.90,0.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
499997,116.30,39.98,116.31,39.89,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
499998,116.37,39.86,116.56,39.78,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
499999,116.50,39.89,116.37,39.94,0.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Count how often one pid takes which click_mode
df_count_pid = df_train[['pid', 'click_mode']]

In [13]:
def one_hot_encode(df_all, column_to_encode, target_column="click_mode"):
    # One hot encode month 
    one_hot = pd.get_dummies(df_all[column_to_encode])
    one_hot.columns = [column_to_encode + "," + str(col) for col in one_hot.columns]
    df_all = df_all.drop(columns=column_to_encode, axis=0)
    df_all = df_all.join(one_hot)
    if target_column is None:
        return df_all
    y = df_all[target_column]
    df_all = df_all.drop(columns=target_column, axis=0)
    df_all = df_all.join(y)
    return df_all

In [22]:
df_count_pid = one_hot_encode(df_count_pid, 'click_mode', None)

In [23]:
df_count_pid.head()

,pid,"click_mode,0.0","click_mode,1.0","click_mode,2.0","click_mode,3.0","click_mode,4.0","click_mode,5.0","click_mode,6.0","click_mode,7.0","click_mode,8.0","click_mode,9.0","click_mode,10.0","click_mode,11.0"
0,-1.0,0,0,0,0,0,0,0,0,0,1,0,0
1,-1.0,0,0,0,0,0,0,0,0,0,1,0,0
2,-1.0,0,1,0,0,0,0,0,0,0,0,0,0
3,-1.0,0,0,0,0,0,0,0,0,0,1,0,0
4,-1.0,0,1,0,0,0,0,0,0,0,0,0,0

In [25]:
df_count_pid=df_count_pid.groupby('pid').sum()

In [27]:
df_count_pid.head()

,"click_mode,0.0","click_mode,1.0","click_mode,2.0","click_mode,3.0","click_mode,4.0","click_mode,5.0","click_mode,6.0","click_mode,7.0","click_mode,8.0","click_mode,9.0","click_mode,10.0","click_mode,11.0"
pid,,,,,,,,,,,,
-1.0,19150.0,20872.0,40175.0,11043.0,4746.0,17429.0,4236.0,22125.0,690.0,15866.0,5700.0,1947.0
100000.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,1.0,0.0
100002.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100005.0,2.0,3.0,10.0,1.0,0.0,3.0,0.0,4.0,0.0,5.0,1.0,1.0
100006.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
df_count_pid.columns

Index(['click_mode,0.0', 'click_mode,1.0', 'click_mode,2.0', 'click_mode,3.0',
       'click_mode,4.0', 'click_mode,5.0', 'click_mode,6.0', 'click_mode,7.0',
       'click_mode,8.0', 'click_mode,9.0', 'click_mode,10.0',
       'click_mode,11.0'],
      dtype='object')

In [31]:
df_train_merged_no_def = pd.merge(df_train, df_count_pid, on='pid')

In [33]:
df_count_pid_min_1 = df_count_pid.copy()

In [40]:
df_count_pid_min_1.loc[df_count_pid_min_1.index == -1] =-1

In [42]:
df_train_merged_no_def_min_1 = pd.merge(df_train, df_count_pid_min_1, on='pid')

In [43]:
df_train_merged_no_def.to_pickle("../data/interim/Train_extern_git_feat_count_nodef.pickle")
df_train_merged_no_def_min_1.to_pickle("../data/interim/Train_extern_git_feat_count_defmin1.pickle")

## df test

In [71]:
df_test_merged_no_def_min_1 = pd.merge(df_test, df_count_pid_min_1, on='pid', how='left')

In [ ]:
df_test_merged_no_def_min_1 = pd.merge(df_test, df_count_pid_min_1, on='pid', how='left')

In [74]:
df_test_merged_no_def_min_1.fillna(-1, inplace=True)

In [75]:
df_test_merged_no_def_min_1.to_pickle("../data/interim/Test_extern_git_feat_count_defmin1.pickle")

In [50]:
df_test_merged_no_def = pd.merge(df_test, df_count_pid, on='pid')
df_count_pid_min_1 = df_count_pid.copy()
df_count_pid_min_1.loc[df_count_pid_min_1.index == -1] =-1
df_test_merged_no_def_min_1 = pd.merge(df_test, df_count_pid_min_1, on='pid')
print(df_count_pid.shape)

df_test_merged_no_def.to_pickle("../data/interim/Test_extern_git_feat_count_nodef.pickle")
df_test_merged_no_def_min_1.to_pickle("../data/interim/Test_extern_git_feat_count_defmin1.pickle")

## feature file

In [44]:
import pickle
with open ('../data/interim/features_pid_all.pickle', 'rb') as fp:
    features = pickle.load(fp)

In [51]:
list(df_test_merged_no_def.columns)

['o1',
 'o2',
 'd1',
 'd2',
 'mode_feas_0',
 'mode_feas_1',
 'mode_feas_2',
 'mode_feas_3',
 'mode_feas_4',
 'mode_feas_5',
 'mode_feas_6',
 'mode_feas_7',
 'mode_feas_8',
 'mode_feas_9',
 'mode_feas_10',
 'mode_feas_11',
 'max_dist',
 'min_dist',
 'mean_dist',
 'std_dist',
 'max_price',
 'min_price',
 'mean_price',
 'std_price',
 'max_eta',
 'min_eta',
 'mean_eta',
 'std_eta',
 'max_dist_mode',
 'min_dist_mode',
 'max_price_mode',
 'min_price_mode',
 'max_eta_mode',
 'min_eta_mode',
 'first_mode',
 'svd_mode_0',
 'svd_mode_1',
 'svd_mode_2',
 'svd_mode_3',
 'svd_mode_4',
 'svd_mode_5',
 'svd_mode_6',
 'svd_mode_7',
 'svd_mode_8',
 'svd_mode_9',
 'svd_fea_0',
 'svd_fea_1',
 'svd_fea_2',
 'svd_fea_3',
 'svd_fea_4',
 'svd_fea_5',
 'svd_fea_6',
 'svd_fea_7',
 'svd_fea_8',
 'svd_fea_9',
 'svd_fea_10',
 'svd_fea_11',
 'svd_fea_12',
 'svd_fea_13',
 'svd_fea_14',
 'svd_fea_15',
 'svd_fea_16',
 'svd_fea_17',
 'svd_fea_18',
 'svd_fea_19',
 'weekday',
 'hour',
 'sid',
 'pid',
 'req_time',
 'o_long',
 'o_lat',
 'd_long',
 'd_lat',
 'distance_query',
 'p0',
 'p1',
 'p2',
 'p3',
 'p4',
 'p5',
 'p6',
 'p7',
 'p8',
 'p9',
 'p10',
 'p11',
 'p12',
 'p13',
 'p14',
 'p15',
 'p16',
 'p17',
 'p18',
 'p19',
 'p20',
 'p21',
 'p22',
 'p23',
 'p24',
 'p25',
 'p26',
 'p27',
 'p28',
 'p29',
 'p30',
 'p31',
 'p32',
 'p33',
 'p34',
 'p35',
 'p36',
 'p37',
 'p38',
 'p39',
 'p40',
 'p41',
 'p42',
 'p43',
 'p44',
 'p45',
 'p46',
 'p47',
 'p48',
 'p49',
 'p50',
 'p51',
 'p52',
 'p53',
 'p54',
 'p55',
 'p56',
 'p57',
 'p58',
 'p59',
 'p60',
 'p61',
 'p62',
 'p63',
 'p64',
 'p65',
 'plan_time',
 'dist_0',
 'price_0',
 'eta_0',
 'dist_1',
 'price_1',
 'eta_1',
 'dist_2',
 'price_2',
 'eta_2',
 'dist_3',
 'price_3',
 'eta_3',
 'dist_4',
 'price_4',
 'eta_4',
 'dist_5',
 'price_5',
 'eta_5',
 'dist_6',
 'price_6',
 'eta_6',
 'dist_7',
 'price_7',
 'eta_7',
 'dist_8',
 'price_8',
 'eta_8',
 'dist_9',
 'price_9',
 'eta_9',
 'dist_10',
 'price_10',
 'eta_10',
 'dist_11',
 'price_11',
 'eta_11',
 'dist_nearest_sub',
 'req_date',
 'req_hour',
 'req_weekend',
 'req_night',
 'req_day',
 'req_evening',
 'is_holiday',
 'max_temp',
 'min_temp',
 'weather',
 'wind',
 'svd_fea_0_2',
 'svd_fea_1_2',
 'svd_fea_2_2',
 'svd_fea_3_2',
 'svd_fea_4_2',
 'svd_fea_5_2',
 'svd_fea_6_2',
 'svd_fea_7_2',
 'svd_fea_8_2',
 'svd_fea_9_2',
 'svd_fea_10_2',
 'svd_fea_11_2',
 'svd_fea_12_2',
 'svd_fea_13_2',
 'svd_fea_14_2',
 'svd_fea_15_2',
 'svd_fea_16_2',
 'svd_fea_17_2',
 'svd_fea_18_2',
 'svd_fea_19_2',
 'dy',
 'dyq',
 'q',
 'qdy',
 'xq',
 'xydy',
 'click_mode,0.0',
 'click_mode,1.0',
 'click_mode,2.0',
 'click_mode,3.0',
 'click_mode,4.0',
 'click_mode,5.0',
 'click_mode,6.0',
 'click_mode,7.0',
 'click_mode,8.0',
 'click_mode,9.0',
 'click_mode,10.0',
 'click_mode,11.0']

In [45]:
features

['o1',
 'o2',
 'd1',
 'd2',
 'mode_feas_0',
 'mode_feas_1',
 'mode_feas_2',
 'mode_feas_3',
 'mode_feas_4',
 'mode_feas_5',
 'mode_feas_6',
 'mode_feas_7',
 'mode_feas_8',
 'mode_feas_9',
 'mode_feas_10',
 'mode_feas_11',
 'max_dist',
 'min_dist',
 'mean_dist',
 'std_dist',
 'max_price',
 'min_price',
 'mean_price',
 'std_price',
 'max_eta',
 'min_eta',
 'mean_eta',
 'std_eta',
 'max_dist_mode',
 'min_dist_mode',
 'max_price_mode',
 'min_price_mode',
 'max_eta_mode',
 'min_eta_mode',
 'first_mode',
 'weekday',
 'hour',
 'distance_query',
 'dist_nearest_sub',
 'dyq',
 'qdy',
 'dy',
 'q',
 'xydy',
 'xq',
 'max_temp',
 'min_temp',
 'wind',
 'req_weekend',
 'is_holiday',
 'p0',
 'p1',
 'p2',
 'p3',
 'p4',
 'p5',
 'p6',
 'p7',
 'p8',
 'p9',
 'p10',
 'p11',
 'p12',
 'p13',
 'p14',
 'p15',
 'p16',
 'p17',
 'p18',
 'p19',
 'p20',
 'p21',
 'p22',
 'p23',
 'p24',
 'p25',
 'p26',
 'p27',
 'p28',
 'p29',
 'p30',
 'p31',
 'p32',
 'p33',
 'p34',
 'p35',
 'p36',
 'p37',
 'p38',
 'p39',
 'p40',
 'p41',
 'p42',
 'p43',
 'p44',
 'p45',
 'p46',
 'p47',
 'p48',
 'p49',
 'p50',
 'p51',
 'p52',
 'p53',
 'p54',
 'p55',
 'p56',
 'p57',
 'p58',
 'p59',
 'p60',
 'p61',
 'p62',
 'p63',
 'p64',
 'p65']

In [52]:
features_new = [
    'click_mode,0.0',
    'click_mode,1.0',
    'click_mode,2.0',
    'click_mode,3.0',
    'click_mode,4.0',
    'click_mode,5.0',
    'click_mode,6.0',
    'click_mode,7.0',
    'click_mode,8.0',
    'click_mode,9.0',
    'click_mode,10.0',
    'click_mode,11.0'
]

In [53]:
features_nodef = features + features_new

In [55]:
import pickle

with open('../data/interim/features_count_pid_mode.pickle', 'wb') as fp:
    pickle.dump(features_nodef, fp)

In [57]:
df_test.shape

(94358, 216)

In [60]:
tmp = pd.read_pickle("../data/interim/Train_extern_git_feat_count_defmin1.pickle")
tmp.shape

(500000, 212)

In [61]:
tmp = pd.read_pickle("../data/interim/Test_extern_git_feat_count_defmin1.pickle")
tmp.shape

(86472, 228)

(86472, 228)