In [3]:
import pandas as pd
import numpy as np
#import matplotlip.pyplot as plt

df_train = pd.read_pickle("../data/external/districts/train_all_first_districts.pickle")
df_train

,sid,click_time,click_mode,pid,req_time,o_long,o_lat,o_district,d_long,d_lat,...,d_district_14,d_district_15,d_district_2,d_district_3,d_district_4,d_district_5,d_district_6,d_district_7,d_district_8,d_district_9
0,2848914.0,2018-11-17 18:42:17,1.0,101804.0,2018-11-17 12:56:15,116.36,40.07,o_district_5,116.00,40.35,...,0,1,0,0,0,0,0,0,0,0
1,2848913.0,2018-11-17 22:25:29,2.0,101804.0,2018-11-17 22:25:16,116.41,39.92,o_district_0,116.39,39.99,...,0,0,0,0,0,0,0,0,0,0
2,2542469.0,2018-11-19 10:30:57,2.0,101804.0,2018-11-19 10:30:50,116.61,40.05,o_district_9,116.41,39.92,...,0,0,0,0,0,0,0,0,0,0
3,381188.0,2018-10-05 12:37:07,2.0,101804.0,2018-10-05 12:37:05,116.42,39.88,o_district_0,116.58,40.08,...,0,0,0,0,0,0,0,0,0,1
4,1601376.0,2018-10-03 13:32:30,1.0,101804.0,2018-10-03 13:27:35,116.37,39.95,o_district_1,116.39,39.89,...,0,0,0,0,0,0,0,0,0,0
5,1601375.0,2018-10-03 12:12:42,1.0,101804.0,2018-10-03 07:36:13,116.18,40.23,o_district_10,116.00,40.36,...,0,1,0,0,0,0,0,0,0,0
6,3064093.0,2018-11-16 13:31:34,2.0,101804.0,2018-11-16 13:30:59,116.41,39.92,o_district_0,116.39,39.91,...,0,0,0,0,0,0,0,0,0,0
7,381189.0,2018-10-05 12:41:08,2.0,101804.0,2018-10-05 12:41:07,116.42,39.88,o_district_0,116.58,40.08,...,0,0,0,0,0,0,0,0,0,1
8,3064092.0,2018-11-16 14:14:56,2.0,101804.0,2018-11-16 14:14:55,116.41,39.92,o_district_0,116.39,39.91,...,0,0,0,0,0,0,0,0,0,0
9,299386.0,2018-10-04 20:55:27,1.0,101804.0,2018-10-04 20:55:20,116.39,39.89,o_district_1,116.41,39.89,...,0,0,0,0,0,0,0,0,0,0
10,2848915.0,2018-11-17 08:08:25,1.0,101804.0,2018-11-17 08:07:52,116.41,39.92,o_district_0,116.00,40.35,...,0,1,0,0,0,0,0,0,0,0
11,3064095.0,2018-11-16 14:20:46,2.0,101804.0,2018-11-16 14:20:40,116.41,39.91,o_district_0,116.39,39.91,...,0,0,0,0,0,0,0,0,0,0
12,2629085.0,2018-10-12 16:28:13,3.0,203797.0,2018-10-12 16:27:55,116.35,40.08,o_district_5,116.33,40.03,...,0,0,0,0,0,1,0,0,0,0
13,1725855.0,2018-11-04 15:32:54,7.0,203797.0,2018-11-04 15:32:52,116.13,39.73,o_district_7,116.21,39.76,...,0,0,0,0,0,0,0,1,0,0
14,1526830.0,2018-11-28 18:16:29,1.0,203797.0,2018-11-28 18:16:05,116.40,39.91,o_district_0,116.39,39.96,...,0,0,0,0,0,0,0,0,0,0
15,1619511.0,2018-10-03 10:38:41,10.0,203797.0,2018-10-03 10:37:57,116.35,39.82,o_district_3,116.32,39.90,...,0,0,0,0,0,0,0,0,0,0
16,2699668.0,2018-10-21 18:37:15,7.0,203797.0,2018-10-21 18:37:07,116.48,39.99,o_district_2,116.37,39.86,...,0,0,0,0,0,0,0,0,0,0
17,2971207.0,2018-11-02 11:28:20,7.0,203797.0,2018-11-02 11:28:17,116.34,40.09,o_district_5,116.84,40.38,...,1,0,0,0,0,0,0,0,0,0
18,564770.0,2018-11-23 12:32:50,2.0,203797.0,2018-11-23 12:32:47,116.55,39.91,o_district_8,116.35,39.91,...,0,0,0,0,0,0,0,0,0,0
19,1452047.0,2018-10-27 00:01:08,1.0,203797.0,2018-10-27 00:00:56,116.53,39.86,o_district_2,116.53,39.87,...,0,0,1,0,0,0,0,0,0,0
20,1000854.0,2018-11-12 20:39:28,1.0,203797.0,2018-11-12 20:39:21,116.20,39.76,o_district_7,116.13,39.73,...,0,0,0,0,0,0,0,1,0,0
21,1597829.0,2018-10-03 12:42:26,1.0,203797.0,2018-10-03 12:42:13,116.28,39.86,o_district_3,116.32,39.89,...,0,0,0,0,0,0,0,0,0,0
22,1879077.0,2018-11-03 11:16:17,7.0,203797.0,2018-11-03 11:16:11,116.33,39.76,o_district_11,116.42,39.80,...,0,0,0,0,0,0,0,0,0,0
23,2268779.0,2018-10-13 17:12:00,2.0,203797.0,2018-10-13 17:10:37,116.35,40.01,o_district_5,116.61,40.07,...,0,0,0,0,0,0,0,0,0,1
24,674078.0,2018-11-15 22:09:53,5.0,203797.0,2018-11-15 22:09:50,116.43,39.92,o_district_2,116.43,39.92,...,0,0,1,0,0,0,0,0,0,0
25,1070006.0,2018-11-08 05:04:17,3.0,203797.0,2018-11-08 05:03:57,116.44,39.84,o_district_2,116.02,40.36,...,0,1,0,0,0,0,0,0,0,0
26,1235882.0,2018-11-22 20:47:14,2.0,203797.0,2018-11-22 20:42:43,116.45,39.91,o_district_2,116.55,39.91,...,0,0,0,0,0,0,0,0,1,0
27,104062.0,2018-10-08 13:57:36,3.0,203797.0,2018-10-08 13:57:29,116.43,39.99,o_district_2,116.62,40.38,...,0,0,0,0,0,0,0,0,0,0
28,2999678.0,2018-11-02 10:08:04,5.0,203797.0,2018-11-02 10:08:00,116.36,39.92,o_district_1,116.37,39.92,...,0,0,0,0,0,0,0,0,0,0
29,1607933.0,2018-10-03 15:03:32,7.0,203797.0,2018-10-03 15:03:25,116.41,39.91,o_district_0,116.23,40.21,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499970,2788629.0,NaN,NaN,171768.0,2018-10-30 09:33:41,116.76,39.94,o_district_8,116.31,39.98,...,0,0,0,0,0,1,0,0,0,0
499971,1923672.0,NaN,NaN,207013.0,2018-11-13 10:23:30,116.41,39.91,o_district_0,116.41,39.91,...,0,0,0,0,0,0,0,0,0,0
499972,2495490.0,NaN,NaN,171849.0,2018-10-07 11:20:54,116.37,39.86,o_district_1,117.12,40.14,...,0,0,0,0,0,0,0,0,0,0
499973,1545216.0,NaN,NaN,126433.0,2018-11-28 07:11:40,116.33,39.98,o_district_5,116.27,40.00,...,0,0,0,0,0,1,0,0,0,0
499974,681660.0,NaN,NaN,174811.0,2018-11-15 14:27:57,116.51,39.89,o_district_2,116.39,40.00,...,0,0,0,0,0,0,0,0,0,0
499975,1536857.0,NaN,NaN,118152.0,2018-11-28 10:31:14,116.09,39.73,o_district_7,116.00,39.72,...,0,0,0,0,0,0,0,1,0,0
499976,709639.0,NaN,NaN,152380.0,2018-10-01 21:47:13,116.32,39.90,o_district_1,116.32,39.89,...,0,0,0,0,0,0,0,0,0,0
499977,704899.0,NaN,NaN,212848.0,2018-11-15 08:34:37,116.64,40.00,o_district_8,116.44,40.08,...,0,0,1,0,0,0,0,0,0,0
499978,3178990.0,NaN,NaN,120272.0,2018-11-21 15:22:16,116.28,39.97,o_district_5,116.27,39.96,...,0,0,0,0,0,1,0,0,0,0
499979,136776.0,NaN,NaN,163854.0,2018-10-08 19:32:29,116.47,39.95,o_district_2,116.47,39.95,...,0,0,1,0,0,0,0,0,0,0
499980,138546.0,NaN,NaN,212655.0,2018-10-08 15:41:55,116.15,40.21,o_district_10,116.42,39.99,...,0,0,0,0,0,0,0,0,0,0
499981,2927394.0,NaN,NaN,202577.0,2018-10-06 11:53:26,116.33,39.94,o_district_5,116.33,39.94,...,0,0,0,0,0,1,0,0,0,0
499982,939520.0,NaN,NaN,125728.0,2018-10-24 21:22:51,116.46,39.84,o_district_2,116.46,39.84,...,0,0,1,0,0,0,0,0,0,0
499983,2956525.0,NaN,NaN,207312.0,2018-11-02 12:24:50,116.67,39.90,o_district_8,116.66,39.90,...,0,0,0,0,0,0,0,0,1,0
499984,3018597.0,NaN,NaN,166726.0,2018-10-22 06:22:02,116.32,39.90,o_district_1,116.37,39.86,...,0,0,0,0,0,0,0,0,0,0
499985,2577595.0,NaN,NaN,216668.0,2018-11-01 14:51:51,116.44,39.96,o_district_2,116.42,39.97,...,0,0,0,0,0,0,0,0,0,0
499986,882060.0,NaN,NaN,188482.0,2018-11-26 12:46:32,116.27,40.04,o_district_5,116.29,40.05,...,0,0,0,0,0,1,0,0,0,0
499987,2256755.0,NaN,NaN,202180.0,2018-10-13 12:44:11,116.31,39.89,o_district_3,116.32,39.89,...,0,0,0,0,0,0,0,0,0,0
499988,1802396.0,NaN,NaN,206413.0,2018-11-29 18:51:00,116.37,39.86,o_district_1,116.26,40.08,...,0,0,0,0,0,1,0,0,0,0
499989,3327896.0,NaN,NaN,208394.0,2018-10-16 12:56:55,116.31,39.99,o_district_5,116.30,39.97,...,0,0,0,0,0,1,0,0,0,0
499990,2522790.0,NaN,NaN,193772.0,2018-10-07 15:24:22,116.62,40.13,o_district_9,116.32,39.90,...,0,0,0,0,0,0,0,0,0,0
499991,191152.0,NaN,NaN,193016.0,2018-10-20 08:41:50,116.42,39.89,o_district_0,116.60,40.08,...,0,0,0,0,0,0,0,0,0,1
499992,535477.0,NaN,NaN,209576.0,2018-11-23 06:57:42,116.31,39.90,o_district_3,116.39,39.90,...,0,0,0,0,0,0,0,0,0,0
499993,3253725.0,NaN,NaN,185226.0,2018-11-25 12:56:37,116.45,39.87,o_district_2,116.51,39.86,...,0,0,1,0,0,0,0,0,0,0
499994,2136824.0,NaN,NaN,112305.0,2018-10-19 18:33:39,116.64,39.84,o_district_8,116.60,39.83,...,0,0,0,0,0,0,0,0,1,0
499995,2574321.0,NaN,NaN,146418.0,2018-11-01 01:18:29,116.34,39.98,o_district_5,116.49,40.01,...,0,0,1,0,0,0,0,0,0,0
499996,2256650.0,NaN,NaN,128778.0,2018-10-13 11:31:39,116.37,39.91,o_district_1,116.27,39.97,...,0,0,0,0,0,1,0,0,0,0
499997,3283826.0,NaN,NaN,180856.0,2018-11-25 15:54:12,116.30,39.97,o_district_5,116.32,39.98,...,0,0,0,0,0,1,0,0,0,0
499998,3239400.0,NaN,NaN,156918.0,2018-11-07 13:00:20,116.37,39.86,o_district_1,116.24,39.93,...,0,0,0,0,1,0,0,0,0,0
499999,3238259.0,NaN,NaN,209690.0,2018-11-07 07:48:43,116.37,39.86,o_district_1,116.60,40.08,...,0,0,0,0,0,0,0,0,0,1

In [4]:
beijing_districts = pd.read_csv("../data/external/districts/beijing_districts.csv")
beijing_districts

       District  No.      o_long      o_lat
0     Dongcheng    1  116.411111  39.923056
1       Xicheng    2  116.360270  39.911510
2      Chaoyang    3  116.443710  39.922478
3       Fengtai    4  116.286700  39.858700
4   Shijingshan    5  116.223000  39.906300
5       Haidian    6  116.298300  39.960000
6     Mentougou    7  116.101400  39.940200
7      Fangshan    8  116.143400  39.748800
8      Tongzhou    9  116.656389  39.910000
9        Shunyi   10  116.655291  40.127577
10    Changping   11  116.231200  40.221000
11       Daxing   12  116.341400  39.726900
12      Huairou   13  116.632000  40.316000
13       Pinggu   14  117.101111  40.142222
14        Miyun   15  116.839444  40.374444
15      Yanqing   16  115.980185  40.464521

In [5]:
# Euclidean Distance Caculator
def dist(a, b, ax=0):
    return np.linalg.norm(a - b, axis=ax)

In [7]:
# Getting coordinates of Starting Points
f1 = df_train['o_lat'].values
f2 = df_train['o_long'].values
P = np.array(list(zip(f1, f2)))
len(P)

500000

In [8]:
array = df_train['o_district'].values
split_array = []
districts = []

for each in array:
    split = each.split(', ')
    split_array.append(split)

for nr in range(len(split_array)):
    z = split_array[nr][0].split('o_district_')
    
    if z[1] not in districts:
        districts.append(z[1])

districts.sort()
len(districts)

16

In [9]:
districts

['0',
 '1',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9']

In [10]:
for district in districts:
    df_train.loc[:,'o_distance_' + district] = np.nan
list(df_train.columns)

['sid',
 'click_time',
 'click_mode',
 'pid',
 'req_time',
 'o_long',
 'o_lat',
 'o_district',
 'd_long',
 'd_lat',
 'd_district',
 'distance_query',
 'p0',
 'p1',
 'p2',
 'p3',
 'p4',
 'p5',
 'p6',
 'p7',
 'p8',
 'p9',
 'p10',
 'p11',
 'p12',
 'p13',
 'p14',
 'p15',
 'p16',
 'p17',
 'p18',
 'p19',
 'p20',
 'p21',
 'p22',
 'p23',
 'p24',
 'p25',
 'p26',
 'p27',
 'p28',
 'p29',
 'p30',
 'p31',
 'p32',
 'p33',
 'p34',
 'p35',
 'p36',
 'p37',
 'p38',
 'p39',
 'p40',
 'p41',
 'p42',
 'p43',
 'p44',
 'p45',
 'p46',
 'p47',
 'p48',
 'p49',
 'p50',
 'p51',
 'p52',
 'p53',
 'p54',
 'p55',
 'p56',
 'p57',
 'p58',
 'p59',
 'p60',
 'p61',
 'p62',
 'p63',
 'p64',
 'p65',
 'plan_time',
 'dist_0',
 'price_0',
 'eta_0',
 'dist_1',
 'price_1',
 'eta_1',
 'dist_2',
 'price_2',
 'eta_2',
 'dist_3',
 'price_3',
 'eta_3',
 'dist_4',
 'price_4',
 'eta_4',
 'dist_5',
 'price_5',
 'eta_5',
 'dist_6',
 'price_6',
 'eta_6',
 'dist_7',
 'price_7',
 'eta_7',
 'dist_8',
 'price_8',
 'eta_8',
 'dist_9',
 'price_9',
 'eta_9',
 'dist_10',
 'price_10',
 'eta_10',
 'dist_11',
 'price_11',
 'eta_11',
 'dist_nearest_sub',
 'req_date',
 'req_hour',
 'req_weekend',
 'req_night',
 'req_day',
 'req_evening',
 'is_holiday',
 'max_temp',
 'min_temp',
 'weather',
 'wind',
 'o_district_0',
 'o_district_1',
 'o_district_10',
 'o_district_11',
 'o_district_12',
 'o_district_13',
 'o_district_14',
 'o_district_15',
 'o_district_2',
 'o_district_3',
 'o_district_4',
 'o_district_5',
 'o_district_6',
 'o_district_7',
 'o_district_8',
 'o_district_9',
 'd_district_0',
 'd_district_1',
 'd_district_10',
 'd_district_11',
 'd_district_12',
 'd_district_13',
 'd_district_14',
 'd_district_15',
 'd_district_2',
 'd_district_3',
 'd_district_4',
 'd_district_5',
 'd_district_6',
 'd_district_7',
 'd_district_8',
 'd_district_9',
 'o_distance_0',
 'o_distance_1',
 'o_distance_10',
 'o_distance_11',
 'o_distance_12',
 'o_distance_13',
 'o_distance_14',
 'o_distance_15',
 'o_distance_2',
 'o_distance_3',
 'o_distance_4',
 'o_distance_5',
 'o_distance_6',
 'o_distance_7',
 'o_distance_8',
 'o_distance_9']

In [11]:
df_train

,sid,click_time,click_mode,pid,req_time,o_long,o_lat,o_district,d_long,d_lat,...,o_distance_14,o_distance_15,o_distance_2,o_distance_3,o_distance_4,o_distance_5,o_distance_6,o_distance_7,o_distance_8,o_distance_9
0,2848914.0,2018-11-17 18:42:17,1.0,101804.0,2018-11-17 12:56:15,116.36,40.07,o_district_5,116.00,40.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2848913.0,2018-11-17 22:25:29,2.0,101804.0,2018-11-17 22:25:16,116.41,39.92,o_district_0,116.39,39.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2542469.0,2018-11-19 10:30:57,2.0,101804.0,2018-11-19 10:30:50,116.61,40.05,o_district_9,116.41,39.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,381188.0,2018-10-05 12:37:07,2.0,101804.0,2018-10-05 12:37:05,116.42,39.88,o_district_0,116.58,40.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1601376.0,2018-10-03 13:32:30,1.0,101804.0,2018-10-03 13:27:35,116.37,39.95,o_district_1,116.39,39.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1601375.0,2018-10-03 12:12:42,1.0,101804.0,2018-10-03 07:36:13,116.18,40.23,o_district_10,116.00,40.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3064093.0,2018-11-16 13:31:34,2.0,101804.0,2018-11-16 13:30:59,116.41,39.92,o_district_0,116.39,39.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,381189.0,2018-10-05 12:41:08,2.0,101804.0,2018-10-05 12:41:07,116.42,39.88,o_district_0,116.58,40.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,3064092.0,2018-11-16 14:14:56,2.0,101804.0,2018-11-16 14:14:55,116.41,39.92,o_district_0,116.39,39.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,299386.0,2018-10-04 20:55:27,1.0,101804.0,2018-10-04 20:55:20,116.39,39.89,o_district_1,116.41,39.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2848915.0,2018-11-17 08:08:25,1.0,101804.0,2018-11-17 08:07:52,116.41,39.92,o_district_0,116.00,40.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,3064095.0,2018-11-16 14:20:46,2.0,101804.0,2018-11-16 14:20:40,116.41,39.91,o_district_0,116.39,39.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2629085.0,2018-10-12 16:28:13,3.0,203797.0,2018-10-12 16:27:55,116.35,40.08,o_district_5,116.33,40.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1725855.0,2018-11-04 15:32:54,7.0,203797.0,2018-11-04 15:32:52,116.13,39.73,o_district_7,116.21,39.76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1526830.0,2018-11-28 18:16:29,1.0,203797.0,2018-11-28 18:16:05,116.40,39.91,o_district_0,116.39,39.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1619511.0,2018-10-03 10:38:41,10.0,203797.0,2018-10-03 10:37:57,116.35,39.82,o_district_3,116.32,39.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2699668.0,2018-10-21 18:37:15,7.0,203797.0,2018-10-21 18:37:07,116.48,39.99,o_district_2,116.37,39.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2971207.0,2018-11-02 11:28:20,7.0,203797.0,2018-11-02 11:28:17,116.34,40.09,o_district_5,116.84,40.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,564770.0,2018-11-23 12:32:50,2.0,203797.0,2018-11-23 12:32:47,116.55,39.91,o_district_8,116.35,39.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1452047.0,2018-10-27 00:01:08,1.0,203797.0,2018-10-27 00:00:56,116.53,39.86,o_district_2,116.53,39.87,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1000854.0,2018-11-12 20:39:28,1.0,203797.0,2018-11-12 20:39:21,116.20,39.76,o_district_7,116.13,39.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1597829.0,2018-10-03 12:42:26,1.0,203797.0,2018-10-03 12:42:13,116.28,39.86,o_district_3,116.32,39.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1879077.0,2018-11-03 11:16:17,7.0,203797.0,2018-11-03 11:16:11,116.33,39.76,o_district_11,116.42,39.80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2268779.0,2018-10-13 17:12:00,2.0,203797.0,2018-10-13 17:10:37,116.35,40.01,o_district_5,116.61,40.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,674078.0,2018-11-15 22:09:53,5.0,203797.0,2018-11-15 22:09:50,116.43,39.92,o_district_2,116.43,39.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1070006.0,2018-11-08 05:04:17,3.0,203797.0,2018-11-08 05:03:57,116.44,39.84,o_district_2,116.02,40.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1235882.0,2018-11-22 20:47:14,2.0,203797.0,2018-11-22 20:42:43,116.45,39.91,o_district_2,116.55,39.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,104062.0,2018-10-08 13:57:36,3.0,203797.0,2018-10-08 13:57:29,116.43,39.99,o_district_2,116.62,40.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2999678.0,2018-11-02 10:08:04,5.0,203797.0,2018-11-02 10:08:00,116.36,39.92,o_district_1,116.37,39.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1607933.0,2018-10-03 15:03:32,7.0,203797.0,2018-10-03 15:03:25,116.41,39.91,o_district_0,116.23,40.21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499970,2788629.0,NaN,NaN,171768.0,2018-10-30 09:33:41,116.76,39.94,o_district_8,116.31,39.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499971,1923672.0,NaN,NaN,207013.0,2018-11-13 10:23:30,116.41,39.91,o_district_0,116.41,39.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499972,2495490.0,NaN,NaN,171849.0,2018-10-07 11:20:54,116.37,39.86,o_district_1,117.12,40.14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499973,1545216.0,NaN,NaN,126433.0,2018-11-28 07:11:40,116.33,39.98,o_district_5,116.27,40.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499974,681660.0,NaN,NaN,174811.0,2018-11-15 14:27:57,116.51,39.89,o_district_2,116.39,40.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499975,1536857.0,NaN,NaN,118152.0,2018-11-28 10:31:14,116.09,39.73,o_district_7,116.00,39.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499976,709639.0,NaN,NaN,152380.0,2018-10-01 21:47:13,116.32,39.90,o_district_1,116.32,39.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499977,704899.0,NaN,NaN,212848.0,2018-11-15 08:34:37,116.64,40.00,o_district_8,116.44,40.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499978,3178990.0,NaN,NaN,120272.0,2018-11-21 15:22:16,116.28,39.97,o_district_5,116.27,39.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499979,136776.0,NaN,NaN,163854.0,2018-10-08 19:32:29,116.47,39.95,o_district_2,116.47,39.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499980,138546.0,NaN,NaN,212655.0,2018-10-08 15:41:55,116.15,40.21,o_district_10,116.42,39.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499981,2927394.0,NaN,NaN,202577.0,2018-10-06 11:53:26,116.33,39.94,o_district_5,116.33,39.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499982,939520.0,NaN,NaN,125728.0,2018-10-24 21:22:51,116.46,39.84,o_district_2,116.46,39.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499983,2956525.0,NaN,NaN,207312.0,2018-11-02 12:24:50,116.67,39.90,o_district_8,116.66,39.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499984,3018597.0,NaN,NaN,166726.0,2018-10-22 06:22:02,116.32,39.90,o_district_1,116.37,39.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499985,2577595.0,NaN,NaN,216668.0,2018-11-01 14:51:51,116.44,39.96,o_district_2,116.42,39.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499986,882060.0,NaN,NaN,188482.0,2018-11-26 12:46:32,116.27,40.04,o_district_5,116.29,40.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499987,2256755.0,NaN,NaN,202180.0,2018-10-13 12:44:11,116.31,39.89,o_district_3,116.32,39.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499988,1802396.0,NaN,NaN,206413.0,2018-11-29 18:51:00,116.37,39.86,o_district_1,116.26,40.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499989,3327896.0,NaN,NaN,208394.0,2018-10-16 12:56:55,116.31,39.99,o_district_5,116.30,39.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499990,2522790.0,NaN,NaN,193772.0,2018-10-07 15:24:22,116.62,40.13,o_district_9,116.32,39.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499991,191152.0,NaN,NaN,193016.0,2018-10-20 08:41:50,116.42,39.89,o_district_0,116.60,40.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499992,535477.0,NaN,NaN,209576.0,2018-11-23 06:57:42,116.31,39.90,o_district_3,116.39,39.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499993,3253725.0,NaN,NaN,185226.0,2018-11-25 12:56:37,116.45,39.87,o_district_2,116.51,39.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499994,2136824.0,NaN,NaN,112305.0,2018-10-19 18:33:39,116.64,39.84,o_district_8,116.60,39.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499995,2574321.0,NaN,NaN,146418.0,2018-11-01 01:18:29,116.34,39.98,o_district_5,116.49,40.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499996,2256650.0,NaN,NaN,128778.0,2018-10-13 11:31:39,116.37,39.91,o_district_1,116.27,39.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499997,3283826.0,NaN,NaN,180856.0,2018-11-25 15:54:12,116.30,39.97,o_district_5,116.32,39.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499998,3239400.0,NaN,NaN,156918.0,2018-11-07 13:00:20,116.37,39.86,o_district_1,116.24,39.93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499999,3238259.0,NaN,NaN,209690.0,2018-11-07 07:48:43,116.37,39.86,o_district_1,116.60,40.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
for p in range(len(P)):
    
    if p % 100 == 0:
        print("Processing row {}".format(str(p)), end="\r")
    
    for i in districts:
        i = int(i)
        x1 = beijing_districts['o_lat'].values[i]
        y1 = beijing_districts['o_long'].values[i]
        C = np.array([x1, y1])
        
        distance = dist(P[p], C)
        df_train.loc[p,'o_distance_' + str(i)] = distance
print("Calculate distances to districts successful")

Calculate distances to districts successful

In [13]:
df_train

,sid,click_time,click_mode,pid,req_time,o_long,o_lat,o_district,d_long,d_lat,...,o_distance_14,o_distance_15,o_distance_2,o_distance_3,o_distance_4,o_distance_5,o_distance_6,o_distance_7,o_distance_8,o_distance_9
0,2848914.0,2018-11-17 18:42:17,1.0,101804.0,2018-11-17 12:56:15,116.36,40.07,o_district_5,116.00,40.35,...,0.567937,0.547637,0.169618,0.223653,0.213464,0.126123,0.289348,0.387408,0.336818,0.300852
1,2848913.0,2018-11-17 22:25:29,2.0,101804.0,2018-11-17 22:25:16,116.41,39.92,o_district_0,116.39,39.99,...,0.625253,0.693718,0.033801,0.137697,0.187501,0.118646,0.309260,0.316836,0.246592,0.321335
2,2542469.0,2018-11-19 10:30:57,2.0,101804.0,2018-11-19 10:30:50,116.61,40.05,o_district_9,116.41,39.92,...,0.397377,0.753986,0.209557,0.375658,0.412818,0.324433,0.520317,0.555371,0.147485,0.089830
3,381188.0,2018-10-05 12:37:07,2.0,101804.0,2018-10-05 12:37:05,116.42,39.88,o_district_0,116.58,40.08,...,0.648389,0.731507,0.048647,0.134991,0.198748,0.145640,0.324238,0.306139,0.238285,0.341550
4,1601376.0,2018-10-03 13:32:30,1.0,101804.0,2018-10-03 13:27:35,116.37,39.95,o_district_1,116.39,39.89,...,0.632875,0.645513,0.078681,0.123590,0.153358,0.072394,0.268779,0.303033,0.289169,0.336042
5,1601375.0,2018-10-03 12:12:42,1.0,101804.0,2018-10-03 07:36:13,116.18,40.23,o_district_10,116.00,40.36,...,0.675078,0.308101,0.405108,0.386327,0.326544,0.294779,0.300270,0.482590,0.573887,0.486202
6,3064093.0,2018-11-16 13:31:34,2.0,101804.0,2018-11-16 13:30:59,116.41,39.92,o_district_0,116.39,39.91,...,0.625253,0.693718,0.033801,0.137697,0.187501,0.118646,0.309260,0.316836,0.246592,0.321335
7,381189.0,2018-10-05 12:41:08,2.0,101804.0,2018-10-05 12:41:07,116.42,39.88,o_district_0,116.58,40.08,...,0.648389,0.731507,0.048647,0.134991,0.198748,0.145640,0.324238,0.306139,0.238285,0.341550
8,3064092.0,2018-11-16 14:14:56,2.0,101804.0,2018-11-16 14:14:55,116.41,39.92,o_district_0,116.39,39.91,...,0.625253,0.693718,0.033801,0.137697,0.187501,0.118646,0.309260,0.316836,0.246592,0.321335
9,299386.0,2018-10-04 20:55:27,1.0,101804.0,2018-10-04 20:55:20,116.39,39.89,o_district_1,116.41,39.89,...,0.660822,0.705707,0.062766,0.107938,0.167794,0.115364,0.292933,0.284164,0.267139,0.356121
10,2848915.0,2018-11-17 08:08:25,1.0,101804.0,2018-11-17 08:07:52,116.41,39.92,o_district_0,116.00,40.35,...,0.625253,0.693718,0.033801,0.137697,0.187501,0.118646,0.309260,0.316836,0.246592,0.321335
11,3064095.0,2018-11-16 14:20:46,2.0,101804.0,2018-11-16 14:20:40,116.41,39.91,o_district_0,116.39,39.91,...,0.632559,0.701594,0.035945,0.133546,0.187037,0.122380,0.310074,0.311546,0.246389,0.327883
12,2629085.0,2018-10-12 16:28:13,3.0,203797.0,2018-10-12 16:27:55,116.35,40.08,o_district_5,116.33,40.03,...,0.571185,0.533497,0.183289,0.230175,0.215176,0.130663,0.285212,0.390355,0.350392,0.308976
13,1725855.0,2018-11-04 15:32:54,7.0,203797.0,2018-11-04 15:32:52,116.13,39.73,o_district_7,116.21,39.76,...,0.958446,0.749644,0.368051,0.202777,0.199326,0.285000,0.212137,0.023087,0.556314,0.658785
14,1526830.0,2018-11-28 18:16:29,1.0,203797.0,2018-11-28 18:16:05,116.40,39.91,o_district_0,116.39,39.96,...,0.639390,0.695513,0.045456,0.124373,0.177039,0.113326,0.300123,0.303033,0.256389,0.335430
15,1619511.0,2018-10-03 10:38:41,10.0,203797.0,2018-10-03 10:37:57,116.35,39.82,o_district_3,116.32,39.90,...,0.739570,0.743082,0.138864,0.074193,0.153547,0.149241,0.276134,0.218525,0.319334,0.433366
16,2699668.0,2018-10-21 18:37:15,7.0,203797.0,2018-10-21 18:37:07,116.48,39.99,o_district_2,116.37,39.86,...,0.526305,0.689192,0.076656,0.233676,0.270286,0.184160,0.381861,0.414098,0.193683,0.222833
17,2971207.0,2018-11-02 11:28:20,7.0,203797.0,2018-11-02 11:28:17,116.34,40.09,o_district_5,116.84,40.38,...,0.574763,0.519358,0.197026,0.237362,0.217795,0.136524,0.281727,0.393788,0.364008,0.317522
18,564770.0,2018-11-23 12:32:50,2.0,203797.0,2018-11-23 12:32:47,116.55,39.91,o_district_8,116.35,39.91,...,0.547253,0.795099,0.107020,0.268251,0.327021,0.256618,0.449615,0.437389,0.106389,0.241715
19,1452047.0,2018-10-27 00:01:08,1.0,203797.0,2018-10-27 00:00:56,116.53,39.86,o_district_2,116.53,39.87,...,0.600340,0.817155,0.106534,0.243303,0.310472,0.252359,0.436039,0.402275,0.135920,0.295458
20,1000854.0,2018-11-12 20:39:28,1.0,203797.0,2018-11-12 20:39:21,116.20,39.76,o_district_7,116.13,39.73,...,0.886809,0.738017,0.292906,0.131372,0.148097,0.222852,0.205412,0.057697,0.480407,0.585152
21,1597829.0,2018-10-03 12:42:26,1.0,203797.0,2018-10-03 12:42:13,116.28,39.86,o_district_3,116.32,39.89,...,0.760020,0.674785,0.175227,0.006825,0.073435,0.101661,0.195780,0.176139,0.379696,0.460913
22,1879077.0,2018-11-03 11:16:17,7.0,203797.0,2018-11-03 11:16:11,116.33,39.76,o_district_11,116.42,39.80,...,0.798170,0.786588,0.198316,0.107780,0.181253,0.202497,0.291084,0.186936,0.359207,0.490843
23,2268779.0,2018-10-13 17:12:00,2.0,203797.0,2018-10-13 17:10:37,116.35,40.01,o_district_5,116.61,40.07,...,0.610225,0.585963,0.128225,0.164008,0.163959,0.071923,0.258213,0.333030,0.322295,0.327150
24,674078.0,2018-11-15 22:09:53,5.0,203797.0,2018-11-15 22:09:50,116.43,39.92,o_district_2,116.43,39.92,...,0.611689,0.706284,0.013932,0.155861,0.207453,0.137640,0.329220,0.333840,0.226610,0.306340
25,1070006.0,2018-11-08 05:04:17,3.0,203797.0,2018-11-08 05:03:57,116.44,39.84,o_district_2,116.02,40.36,...,0.667223,0.775536,0.082561,0.154436,0.226902,0.185685,0.353115,0.310305,0.227430,0.359236
26,1235882.0,2018-11-22 20:47:14,2.0,203797.0,2018-11-22 20:42:43,116.45,39.91,o_district_2,116.55,39.91,...,0.606115,0.726787,0.013974,0.171168,0.227030,0.159728,0.349906,0.346394,0.206389,0.299139
27,104062.0,2018-10-08 13:57:36,3.0,203797.0,2018-10-08 13:57:29,116.43,39.99,o_district_2,116.62,40.38,...,0.561642,0.653838,0.068900,0.194357,0.223282,0.135074,0.332352,0.374589,0.240108,0.263976
28,2999678.0,2018-11-02 10:08:04,5.0,203797.0,2018-11-02 10:08:00,116.36,39.92,o_district_1,116.37,39.92,...,0.660595,0.663900,0.083747,0.095554,0.137683,0.073532,0.259388,0.276089,0.296558,0.360950
29,1607933.0,2018-10-03 15:03:32,7.0,203797.0,2018-10-03 15:03:25,116.41,39.91,o_district_0,116.23,40.21,...,0.632559,0.701594,0.035945,0.133546,0.187037,0.122380,0.310074,0.311546,0.246389,0.327883
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499970,2788629.0,NaN,NaN,171768.0,2018-10-30 09:33:41,116.76,39.94,o_district_8,116.31,39.98,...,0.441648,0.939805,0.316775,0.480232,0.538056,0.462133,0.658600,0.645564,0.107867,0.214823
499971,1923672.0,NaN,NaN,207013.0,2018-11-13 10:23:30,116.41,39.91,o_district_0,116.41,39.91,...,0.632559,0.701594,0.035945,0.133546,0.187037,0.122380,0.310074,0.311546,0.246389,0.327883
499972,2495490.0,NaN,NaN,171849.0,2018-10-07 11:20:54,116.37,39.86,o_district_1,117.12,40.14,...,0.696441,0.719306,0.096626,0.083310,0.154119,0.123048,0.280318,0.252414,0.290721,0.391137
499973,1545216.0,NaN,NaN,126433.0,2018-11-28 07:11:40,116.33,39.98,o_district_5,116.27,40.00,...,0.644297,0.597604,0.127431,0.128797,0.129926,0.037482,0.232039,0.297108,0.333811,0.357202
499974,681660.0,NaN,NaN,174811.0,2018-11-15 14:27:57,116.51,39.89,o_district_2,116.39,40.00,...,0.585849,0.781523,0.073819,0.225483,0.287463,0.222973,0.411672,0.392852,0.147749,0.278482
499975,1536857.0,NaN,NaN,118152.0,2018-11-28 10:31:14,116.09,39.73,o_district_7,116.00,39.72,...,0.988420,0.742685,0.402689,0.235063,0.220841,0.310305,0.210509,0.056613,0.594303,0.691102
499976,709639.0,NaN,NaN,152380.0,2018-10-01 21:47:13,116.32,39.90,o_district_1,116.32,39.89,...,0.703505,0.658907,0.125736,0.053053,0.097204,0.063804,0.222266,0.232484,0.336538,0.405230
499977,704899.0,NaN,NaN,212848.0,2018-11-15 08:34:37,116.64,40.00,o_district_8,116.44,40.08,...,0.424248,0.806930,0.211044,0.380508,0.427398,0.344033,0.541910,0.556519,0.091480,0.128490
499978,3178990.0,NaN,NaN,120272.0,2018-11-21 15:22:16,116.28,39.97,o_district_5,116.27,39.96,...,0.690328,0.578308,0.170468,0.111501,0.085479,0.020854,0.181069,0.259979,0.381141,0.407031
499979,136776.0,NaN,NaN,163854.0,2018-10-08 19:32:29,116.47,39.95,o_district_2,116.47,39.95,...,0.562709,0.710388,0.038061,0.204779,0.250836,0.171991,0.368730,0.383600,0.190633,0.256644
499980,138546.0,NaN,NaN,212655.0,2018-10-08 15:41:55,116.15,40.21,o_district_10,116.42,39.99,...,0.708784,0.305971,0.411016,0.376960,0.312350,0.290677,0.274142,0.461247,0.588583,0.511969
499981,2927394.0,NaN,NaN,202577.0,2018-10-06 11:53:26,116.33,39.94,o_district_5,116.33,39.94,...,0.669533,0.630470,0.115052,0.092112,0.112182,0.037482,0.228600,0.267165,0.327765,0.375499
499982,939520.0,NaN,NaN,125728.0,2018-10-24 21:22:51,116.46,39.84,o_district_2,116.46,39.84,...,0.655445,0.787559,0.084071,0.174306,0.246099,0.201363,0.372336,0.329474,0.208491,0.347619
499983,2956525.0,NaN,NaN,207312.0,2018-11-02 12:24:50,116.67,39.90,o_district_8,116.66,39.90,...,0.503794,0.891363,0.227404,0.385519,0.447044,0.376511,0.570019,0.547877,0.016890,0.228052
499984,3018597.0,NaN,NaN,166726.0,2018-10-22 06:22:02,116.32,39.90,o_district_1,116.37,39.86,...,0.703505,0.658907,0.125736,0.053053,0.097204,0.063804,0.222266,0.232484,0.336538,0.405230
499985,2577595.0,NaN,NaN,216668.0,2018-11-01 14:51:51,116.44,39.96,o_district_2,116.42,39.97,...,0.575603,0.682621,0.037705,0.183746,0.223546,0.141700,0.339178,0.364111,0.222091,0.272823
499986,882060.0,NaN,NaN,188482.0,2018-11-26 12:46:32,116.27,40.04,o_district_5,116.29,40.05,...,0.660393,0.514014,0.209730,0.182068,0.141720,0.084858,0.195923,0.317530,0.407672,0.395119
499987,2256755.0,NaN,NaN,202180.0,2018-10-13 12:44:11,116.31,39.89,o_district_3,116.32,39.89,...,0.717633,0.662459,0.137598,0.039020,0.088514,0.070971,0.214555,0.218387,0.346966,0.419129
499988,1802396.0,NaN,NaN,206413.0,2018-11-29 18:51:00,116.37,39.86,o_district_1,116.26,40.08,...,0.696441,0.719306,0.096626,0.083310,0.154119,0.123048,0.280318,0.252414,0.290721,0.391137
499989,3327896.0,NaN,NaN,208394.0,2018-10-16 12:56:55,116.31,39.99,o_district_5,116.30,39.97,...,0.654300,0.577882,0.149792,0.133351,0.120726,0.032201,0.214462,0.293143,0.355507,0.371690
499990,2522790.0,NaN,NaN,193772.0,2018-10-07 15:24:22,116.62,40.13,o_district_9,116.32,39.90,...,0.328494,0.721989,0.272293,0.429759,0.455687,0.363856,0.552241,0.610296,0.222989,0.035374
499991,191152.0,NaN,NaN,193016.0,2018-10-20 08:41:50,116.42,39.89,o_district_0,116.60,40.08,...,0.640796,0.723541,0.040212,0.136925,0.197673,0.140395,0.322531,0.310556,0.237234,0.334372
499992,535477.0,NaN,NaN,209576.0,2018-11-23 06:57:42,116.31,39.90,o_district_3,116.39,39.90,...,0.710921,0.653806,0.135586,0.047419,0.087228,0.061130,0.212438,0.224982,0.346533,0.413542
499993,3253725.0,NaN,NaN,185226.0,2018-11-25 12:56:37,116.45,39.87,o_district_2,116.51,39.86,...,0.637284,0.757748,0.052854,0.163691,0.229884,0.176388,0.355598,0.329686,0.210229,0.329379
499994,2136824.0,NaN,NaN,112305.0,2018-10-19 18:33:39,116.64,39.84,o_district_8,116.60,39.83,...,0.570446,0.908506,0.212914,0.353795,0.422238,0.362159,0.547841,0.504905,0.071893,0.287983
499995,2574321.0,NaN,NaN,146418.0,2018-11-01 01:18:29,116.34,39.98,o_district_5,116.49,40.01,...,0.636420,0.603513,0.118594,0.132494,0.138278,0.046248,0.241897,0.303488,0.324040,0.348120
499996,2256650.0,NaN,NaN,128778.0,2018-10-13 11:31:39,116.37,39.91,o_district_1,116.27,39.97,...,0.660368,0.677827,0.074759,0.097829,0.147047,0.087412,0.270292,0.278088,0.286389,0.358791
499997,3283826.0,NaN,NaN,180856.0,2018-11-25 15:54:12,116.30,39.97,o_district_5,116.32,39.98,...,0.674222,0.588925,0.151363,0.112092,0.099933,0.010143,0.200823,0.271022,0.361404,0.388667
499998,3239400.0,NaN,NaN,156918.0,2018-11-07 13:00:20,116.37,39.86,o_district_1,116.24,39.93,...,0.696441,0.719306,0.096626,0.083310,0.154119,0.123048,0.280318,0.252414,0.290721,0.391137
499999,3238259.0,NaN,NaN,209690.0,2018-11-07 07:48:43,116.37,39.86,o_district_1,116.60,40.08,...,0.696441,0.719306,0.096626,0.083310,0.154119,0.123048,0.280318,0.252414,0.290721,0.391137

In [14]:
df_train.to_pickle("../data/external/districts/train_all_first_final.pickle")

In [17]:
for i in districts:
        i = int(i)
        x1 = beijing_districts['o_lat'].values[i]
        y1 = beijing_districts['o_long'].values[i]
        C = np.array([x1, y1])
        print(C)

[ 39.923056 116.411111]
[ 39.91151 116.36027]
[ 40.221  116.2312]
[ 39.7269 116.3414]
[ 40.316 116.632]
[ 40.142222 117.101111]
[ 40.374444 116.839444]
[ 40.464521 115.980185]
[ 39.922478 116.44371 ]
[ 39.8587 116.2867]
[ 39.9063 116.223 ]
[ 39.96   116.2983]
[ 39.9402 116.1014]
[ 39.7488 116.1434]
[ 39.91     116.656389]
[ 40.127577 116.655291]

In [20]:
# Setting Centroids
x1 = beijing_districts['o_lat'].values
y1 = beijing_districts['o_long'].values
C = np.array(list(zip(x1, y1)))

for i in districts:
    i = int(i)
    y = C[i]
    print(y)
    # for each in C:
    #    x = each
    #    print(x)

[ 39.923056 116.411111]
[ 39.91151 116.36027]
[ 40.221  116.2312]
[ 39.7269 116.3414]
[ 40.316 116.632]
[ 40.142222 117.101111]
[ 40.374444 116.839444]
[ 40.464521 115.980185]
[ 39.922478 116.44371 ]
[ 39.8587 116.2867]
[ 39.9063 116.223 ]
[ 39.96   116.2983]
[ 39.9402 116.1014]
[ 39.7488 116.1434]
[ 39.91     116.656389]
[ 40.127577 116.655291]